/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte;

public class PascalsDreieck {
    int zeilen;
    int[][] dreieck;

    public PascalsDreieck(int zeilen) {
        this.zeilen = zeilen;
        initDreieck();
    }

    public void initDreieck() {
        dreieck = new int[zeilen][];
        for (int i = 0; i < zeilen; i++){
            dreieck[i] = new int[i+1];
        }
    }

    public void berechneDreieck(){
        for (int i = 0; i < dreieck.length; i++){
            dreieck[i][0] = 1;
            dreieck[i][dreieck[i].length-1] = 1;

            for (int j = 1; j < dreieck[i].length-1; j++){
                dreieck[i][j] = dreieck[i-1][j-1] + dreieck[i-1][j];
            }
        }
    }

    public static void main(String[] args) {
        PascalsDreieck d = new PascalsDreieck(6);
        d.initDreieck();
        d.berechneDreieck();

        for (int[] zeile:d.dreieck){
            for (int num:zeile) System.out.print(num + " ");
            System.out.println();
        }
    }
}
